---
# tasks file for mariadb
- name: Install MariaDB {{ mariadb_version }}
  become: yes
  zypper:
    name: "{{ mysql_packages }}"
    state: installed

- name: Install dependencies
  become: yes
  zypper:
    name:
      - python3
      - python3-pip
      - python3-setuptools
    state: latest

- name: Install required pip packages
  pip:
    name:
      - PyMySQL
    executable: pip


- name: Start MariaDB Service
  become: yes
  service:
    name: mariadb
    state: started
    enabled: true

#
#- name: Set Magento Database User
#  mysql_user:
#    name: "{{ db_user }}"
#    password: "{{ db_password }}"
#    priv: "*.*:ALL"
#    state: present
##
#- name: Set Magento Database
#  mysql_db:
#    name: "{{ db_name }}"
#    state: present
